config/routes.rb
Massgameshvz::Application.routes.draw do

  resources :squads do
    collection do
      get :usernames
    end
  end

  get "welcome/index"

  resources :games do
    collection do
      get '_show'
    end
  end
  resources :game_participations
  resources :users do
    member do
      get :confirm
    end
    collection do
      post :resend_confirmation
    end
  end
  resources :user_sessions
  resources :self_bites
  resources :bites do
    new do
      get :report
    end
  end
  resources :bite_shares do
    member do
      get :share
    end
    collection do
      get :usernames
    end
  end
  resources :vaccines do
    collection do
      get :enter
      put :take
    end
  end
  resources :events do
    collection do
      get '_show'
    end
  end
  resources :posts

  resources :player_statuses

  match "login", :to => "user_sessions#new"
  match "logout", :to => "user_sessions#destroy"
  match "register", :to => "users#new"
  match "admin", :to => 'admin#index'
  match "players", :to => 'games#index'
  match 'ask_about_game_registration', :to => 'game_participations#ask_about_game_registration'
  match 'existing_user_registration', :to => 'game_participations#new'
  
  
  namespace :admin do
    resources :living_areas
    resources :humans
    resources :zombies
    resources :original_zombies do 
     member do
       put 'make_zombie'
       put 'make_regular'
     end
    end
    resources :squads do
      collection do
        get :usernames
      end
    end
    resources :vaccines
    resources :pseudo_bites
    resources :users do
      member do
        put :update_user_number 
      end
      collection do
        get 'get_creatures'
      end
    end
    resources :sarcastic_comments
    resources :games
    resources :events
    resources :email_domains
    resource :mailer
    resources :posts
    
    #misc admin tasks, not really a resource but easier to work with this way
    resources :misc_tasks do
      collection do
        get 'pause_game_form'
        put 'pause_game'
        put 'unpause_game'
        put 'set_unassigned_to_human'
        put 'resurrect_dead'
        put 'increase_zombie_expires_at'
      end
    end
  end

  root :to => "welcome#index"
end

app/controllers/admin/original_zombies_controller.rb
class Admin::OriginalZombiesController < AdminController
  def index
    @game_participations = GameParticipation::OriginalZombiesReport.original_zombies_and_zombie_requests
  end

  def show

  end

  def make_zombie
    @game_participation = GameParticipation.find(params[:id])
    @game_participation.creature = Zombie::ORIGINAL
    @game_participation.save
    redirect_to admin_original_zombies_url
  end

  def make_regular
    @game_participation = GameParticipation.find(params[:id])
    @game_participation.creature = Human::NORMAL
    @game_participation.save
    redirect_to admin_original_zombies_url
  end

end

app/views/admin/original_zombies/index.html.erb
<p>
  You can set the users to either zombie or human below. Zombies will be considered original zombies,
  and humans will be considered normal humans. If you want to assign a user to something other than
  an original zombie, or normal human, visit the <%=link_to 'users', admin_users_url %> page to edit the user
  manually. Keep in mind that this only lists people who have requested to be original zombies. After you
  are done assigning zombies, visit the <%=link_to 'misc tasks', admin_misc_tasks_url %> to assign all unassigned 
  users to normal humans.
</p>
<table>
  <tr>
    <th>username</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>add/remove</th>
  </tr>
  <% for game_participation in @game_participations %>
  <% user = game_participation.user %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td>
      <% if game_participation.original_zombie? %>
        <%= form_for game_participation, :url => make_regular_admin_original_zombie_url(:id => game_participation.id), :html => {:style => 'display: inline;'} do %>
          <input type='submit' value='humanize'>
        <% end %>
      <% else %>
        <%= form_for game_participation, :url => make_zombie_admin_original_zombie_url(:id => game_participation.id), :html => {:style => 'display: inline;'} do %>
          <input type='submit' value='make original'>
        <% end %>
      <%end %>
    </td>
  </tr>
  <% end %>
</table>