config/routes.rb
Massgameshvz::Application.routes.draw do

  resources :squads do
    collection do
      get :usernames
    end
  end

  get "welcome/index"

  resources :games do
    collection do
      get '_show'
    end
  end
  resources :game_participations
  resources :users do
    member do
      get :confirm
    end
    collection do
      post :resend_confirmation
    end
  end
  resources :user_sessions
  resources :self_bites
  resources :bites do
    new do
      get :report
    end
  end
  resources :bite_shares do
    member do
      get :share
    end
    collection do
      get :usernames
    end
  end
  resources :vaccines do
    collection do
      get :enter
      put :take
    end
  end
  resources :events do
    collection do
      get '_show'
    end
  end
  resources :posts

  resources :player_statuses

  match "login", :to => "user_sessions#new"
  match "logout", :to => "user_sessions#destroy"
  match "register", :to => "users#new"
  match "admin", :to => 'admin#index'
  match "players", :to => 'games#index'
  match 'ask_about_game_registration', :to => 'game_participations#ask_about_game_registration'
  match 'existing_user_registration', :to => 'game_participations#new'
  
  
  namespace :admin do
    resources :living_areas
    resources :humans
    resources :zombies
    resources :original_zombies do 
     member do
       put 'make_zombie'
       put 'make_regular'
     end
    end
    resources :squads do
      collection do
        get :usernames
      end
    end
    resources :vaccines
    resources :pseudo_bites
    resources :users do
      member do
        put :update_user_number 
      end
      collection do
        get 'get_creatures'
      end
    end
    resources :sarcastic_comments
    resources :games
    resources :events
    resources :email_domains
    resource :mailer
    resources :posts
    
    #misc admin tasks, not really a resource but easier to work with this way
    resources :misc_tasks do
      collection do
        get 'pause_game_form'
        put 'pause_game'
        put 'unpause_game'
        put 'set_unassigned_to_human'
        put 'resurrect_dead'
        put 'increase_zombie_expires_at'
      end
    end
  end

  root :to => "welcome#index"
end

app/models/living_area.rb
class LivingArea < ActiveRecord::Base
  has_many :game_participations
end

app/controllers/admin/living_areas_controller.rb
class Admin::LivingAreasController < AdminController
  
  before_filter :get_living_area, :only => [:show, :update, :edit, :destroy]

  def index
    @living_areas = LivingArea.all
  end
  
  def edit
  end
  
  def destroy
    @living_area.delete
    redirect_to admin_living_areas_url()
  end
  
  def show
  end
  
  def new
    @living_area = LivingArea.new
  end
  
  def create
    @living_area = LivingArea.new(params[:living_area])
    if @living_area.save
      redirect_to admin_living_areas_url()
    else
      render :action => 'new'
    end
  end
  
  def update
    @living_area.update_attributes params[:living_areas]
    redirect_to admin_living_areas_url()
  end
  
  private
  
  def get_living_area
    @living_area = LivingArea.find(params[:id])
  end
  
end

app/views/admin/living_areas/edit.html.erb
<% form_for @living_area, :url => admin_living_area_url(@living_area) do |f|%>
  <p>
    <%= f.label :name%>
    <%= f.text_field :name%>
  </p>
  <p>
    <%= submit_tag :save%>
  </p>
<% end %>

app/views/admin/living_areas/index.html.erb
<table>
  <tr>
    <th>
      name
    </th>
  </tr>
  <%@living_areas.each do |la|%>
    <tr>
      <td>
        <%=h(la.name)%>
      </td>
      <td>
        <%= link_to 'edit', edit_admin_living_area_url(la)%> |
        <%= link_to 'delete', admin_living_area_url(la), :method => 'delete', :confirm => 'are you sure?'%>
      </td>
    </tr>
  <%end%>
</table>
<%=link_to 'new', new_admin_living_area_url()%>

app/views/admin/living_areas/new.html.erb
<% form_for @living_area, :url => admin_living_areas_url() do |f|%>
  <p>
    <%= f.label :name%>
    <%= f.text_field :name%>
  </p>
  <p>
    <%= submit_tag :save%>
  </p>
<% end %>