config/routes.rb
Massgameshvz::Application.routes.draw do

  resources :squads do
    collection do
      get :usernames
    end
  end

  get "welcome/index"

  resources :games do
    collection do
      get '_show'
    end
  end
  resources :game_participations
  resources :users do
    member do
      get :confirm
    end
    collection do
      post :resend_confirmation
    end
  end
  resources :user_sessions
  resources :self_bites
  resources :bites do
    new do
      get :report
    end
  end
  resources :bite_shares do
    member do
      get :share
    end
    collection do
      get :usernames
    end
  end
  resources :vaccines do
    collection do
      get :enter
      put :take
    end
  end
  resources :events do
    collection do
      get '_show'
    end
  end
  resources :posts

  resources :player_statuses

  match "login", :to => "user_sessions#new"
  match "logout", :to => "user_sessions#destroy"
  match "register", :to => "users#new"
  match "admin", :to => 'admin#index'
  match "players", :to => 'games#index'
  match 'ask_about_game_registration', :to => 'game_participations#ask_about_game_registration'
  match 'existing_user_registration', :to => 'game_participations#new'
  
  
  namespace :admin do
    resources :living_areas
    resources :humans
    resources :zombies
    resources :original_zombies do 
     member do
       put 'make_zombie'
       put 'make_regular'
     end
    end
    resources :squads do
      collection do
        get :usernames
      end
    end
    resources :vaccines
    resources :pseudo_bites
    resources :users do
      member do
        put :update_user_number 
      end
      collection do
        get 'get_creatures'
      end
    end
    resources :sarcastic_comments
    resources :games
    resources :events
    resources :email_domains
    resource :mailer
    resources :posts
    
    #misc admin tasks, not really a resource but easier to work with this way
    resources :misc_tasks do
      collection do
        get 'pause_game_form'
        put 'pause_game'
        put 'unpause_game'
        put 'set_unassigned_to_human'
        put 'resurrect_dead'
        put 'increase_zombie_expires_at'
      end
    end
  end

  root :to => "welcome#index"
end

app/controllers/admin/misc_tasks_controller.rb
class Admin::MiscTasksController < AdminController
  
  
  def index
  end
  
  def pause_game_form
  end
  
  def pause_game
    unless Game.current.paused?
      ActiveRecord::Base.transaction do
        GameParticipation.lock
        Game.current.update_attributes(params[:game])
      end
    end
    flash[:notice] = "The game is paused until #{params[:game][:pause_ends_at]}"
    redirect_to admin_misc_tasks_url
  end
  
  def unpause_game
    if Game.current.paused?
      ActiveRecord::Base.transaction do
        GameParticipation.lock
        Game.current.unpause_game
      end
    end
    flash[:notice] = "The game has been unpaused"
    redirect_to admin_misc_tasks_url
  end
  
  def increase_zombie_expires_at
    Game.transaction do
      GameParticipation.transaction do
        Game.current.reward_zombies params[:hours]
      end
    end
    redirect_to admin_misc_tasks_url
  end

  def set_unassigned_to_human
    GameParticipation.update_all(["creature_type = 'Human', creature_id = ?", Human::NORMAL], ['creature_type is null AND game_id = ?', Game.current.id])
    redirect_to admin_misc_tasks_url
  end

  def resurrect_dead
    GameParticipation.update_all(['zombie_expires_at = ?', Time.now + Game.current.time_per_food], ['creature_type = "Zombie" AND game_id = ?', Game.current.id])
    redirect_to admin_misc_tasks_url
  end

end

app/views/admin/misc_tasks/index.html.erb
<h3>Set Unassigned to Human</h3>
This will cause all unassigned users who are confirmed to become regular humans. 
<% form_tag set_unassigned_to_human_admin_misc_tasks_url, :method => :put do %>
  <%= submit_tag 'unassigned to human', :confirm => 'are you sure you want to assign all unassigned as humans?'%>
<% end %>
<hr>

<h3>Resurrect Dead</h3>
This will move all zombie expirations, for both dead and alive humans ahead by the value
of food game attribute. This should be used at the end of the game to bring the dead back
for the final mission.
<% form_tag resurrect_dead_admin_misc_tasks_url, :method => :put do %>
  <%= submit_tag 'resurrect dead', :confirm => 'are you sure you want to resurrect the dead?' %>
<% end %>
<hr>

<h3>Pause Game</h3>
Click Below to pause/unpause game.<br /> <%= link_to 'Pause Game', pause_game_form_admin_misc_tasks_url %>
<hr>

<h3>Reward Zombies (hint, use negative numbers to punish zombies!)</h3>
<%= form_tag increase_zombie_expires_at_admin_misc_tasks_url, :method => :put do %>
Hours: <%= text_field_tag 'hours'%><br />
<%= submit_tag 'Reward Zombies'%>
<% end %>

app/views/admin/misc_tasks/pause_game_form.html.erb
<% unless Game.current.paused? %>
  <%= form_for Game.current, :url => pause_game_admin_misc_tasks_url do |f| %>
  <p>
    <%= f.label :pause_ends_at, "Pause Game Until" %>
    <%= f.datetime_select :pause_ends_at %>
  </p>
  <p>
    <%= f.submit 'Pause Game'%>
  </p>
  <% end %>
<% else %>
  <%= form_for Game.current, :url => unpause_game_admin_misc_tasks_url do |f| %>
  <p>
    <%= f.submit 'Unpause Game'%>
  </p>
  <% end %>
<% end %>

app/views/admin/misc_tasks/resurrect_dead.html.erb
<h1>Admin::MiscTasks#resurrect_dead</h1>
<p>Find me in app/views/admin/misc_tasks/resurrect_dead.html.erb</p>

app/views/admin/misc_tasks/set_game_attributes.html.erb
<h1>Admin::MiscTasks#set_game_attributes</h1>
<p>Find me in app/views/admin/misc_tasks/set_game_attributes.html.erb</p>

app/views/admin/misc_tasks/set_unassigned_to_human.html.erb
<h1>Admin::MiscTasks#set_unassigned_to_human</h1>
<p>Find me in app/views/admin/misc_tasks/set_unassigned_to_human.html.erb</p>

app/views/admin/misc_tasks/view_game_attributes.html.erb
<h1>Admin::MiscTasks#view_game_attributes</h1>
<p>Find me in app/views/admin/misc_tasks/view_game_attributes.html.erb</p>