config/routes.rb
Massgameshvz::Application.routes.draw do

  resources :squads do
    collection do
      get :usernames
    end
  end

  get "welcome/index"

  resources :games do
    collection do
      get '_show'
    end
  end
  resources :game_participations
  resources :users do
    member do
      get :confirm
    end
    collection do
      post :resend_confirmation
    end
  end
  resources :user_sessions
  resources :self_bites
  resources :bites do
    new do
      get :report
    end
  end
  resources :bite_shares do
    member do
      get :share
    end
    collection do
      get :usernames
    end
  end
  resources :vaccines do
    collection do
      get :enter
      put :take
    end
  end
  resources :events do
    collection do
      get '_show'
    end
  end
  resources :posts

  resources :player_statuses

  match "login", :to => "user_sessions#new"
  match "logout", :to => "user_sessions#destroy"
  match "register", :to => "users#new"
  match "admin", :to => 'admin#index'
  match "players", :to => 'games#index'
  match 'ask_about_game_registration', :to => 'game_participations#ask_about_game_registration'
  match 'existing_user_registration', :to => 'game_participations#new'
  
  
  namespace :admin do
    resources :living_areas
    resources :humans
    resources :zombies
    resources :original_zombies do 
     member do
       put 'make_zombie'
       put 'make_regular'
     end
    end
    resources :squads do
      collection do
        get :usernames
      end
    end
    resources :vaccines
    resources :pseudo_bites
    resources :users do
      member do
        put :update_user_number 
      end
      collection do
        get 'get_creatures'
      end
    end
    resources :sarcastic_comments
    resources :games
    resources :events
    resources :email_domains
    resource :mailer
    resources :posts
    
    #misc admin tasks, not really a resource but easier to work with this way
    resources :misc_tasks do
      collection do
        get 'pause_game_form'
        put 'pause_game'
        put 'unpause_game'
        put 'set_unassigned_to_human'
        put 'resurrect_dead'
        put 'increase_zombie_expires_at'
      end
    end
  end

  root :to => "welcome#index"
end

app/models/email_domain.rb
class EmailDomain < ActiveRecord::Base
end

app/controllers/admin/email_domains_controller.rb
class Admin::EmailDomainsController < AdminController
  def index
    @email_domains = EmailDomain.all
  end
  
  def new
    @email_domain = EmailDomain.new
  end
  
  def edit
    @email_domain = EmailDomain.find(params[:id])
  end
  
  def update
    @email_domain = EmailDomain.find(params[:id])
    if @email_domain.update_attributes(params[:email_domain])
      redirect_to admin_email_domains_url
    else
      render :action => 'new'
    end
  end
  
  def create
    @email_domain = EmailDomain.new(params[:email_domain])
    if @email_domain.save
      redirect_to admin_email_domains_url
    else
      render :action => 'new'
    end
  end
end

app/views/admin/email_domains/_form.html.erb
<p>
  <%= f.label :description %>
  <%= f.text_field :description %>
</p>
<p>
  <%= f.label :rule %>
  <%= f.text_field :rule %>
</p>
<p>
  <%= f.submit %>
</p>

app/views/admin/email_domains/edit.html.erb
<%= form_for @email_domain, :url => admin_email_domain_url(@email_domain) do |f| %>
<%= render :partial => 'form', :locals => {:f => f}%>
<% end %>

app/views/admin/email_domains/index.html.erb
<h2>Email Domains</h2>
<table>
  <tr>
    <th>description</th>
    <th>rule</th>
  </tr>
  <% for email_domain in @email_domains %>
    <tr>
      <td><%= email_domain.description %></td>
      <td><%= email_domain.rule %></td>
      <td><%= link_to 'edit', edit_admin_email_domain_url(email_domain) %>
    </tr>
  <% end %>
</table>
<%= link_to 'Add Domain', new_admin_email_domain_url %>

app/views/admin/email_domains/new.html.erb
<%= form_for @email_domain, :url => admin_email_domains_url do |f| %>
<%= render :partial => 'form', :locals => {:f => f}%>
<% end %>